//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeaFoodProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHITIETHOADON
    {
        public int id { get; set; }
        public string MSHAISAN { get; set; }
        public Nullable<int> MAHD { get; set; }
        public Nullable<int> SOLUONG { get; set; }
        public Nullable<double> GIATIEN { get; set; }
    
        public virtual HAISAN HAISAN { get; set; }
        public virtual HOADON HOADON { get; set; }
    }
}
