//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeaFoodProject
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KingOceanEntities : DbContext
    {
        public KingOceanEntities()
            : base("name=KingOceanEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<CHITIETDONDAT> CHITIETDONDAT { get; set; }
        public DbSet<CHITIETHOADON> CHITIETHOADON { get; set; }
        public DbSet<CHUCVU> CHUCVU { get; set; }
        public DbSet<DONDAT> DONDAT { get; set; }
        public DbSet<DONVITINH> DONVITINH { get; set; }
        public DbSet<HAISAN> HAISAN { get; set; }
        public DbSet<HOADON> HOADON { get; set; }
        public DbSet<KHACHHANG> KHACHHANG { get; set; }
        public DbSet<LOAIHAISAN> LOAIHAISAN { get; set; }
        public DbSet<NHANVIEN> NHANVIEN { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<TRANGTHAI> TRANGTHAI { get; set; }
    }
}
